version: "3"
services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://merch:merch2023!@db:5432/merchandise
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=merchandise
      - POSTGRES_USER=merch
      - POSTGRES_PASSWORD=merch2023!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: